# Import Required Libraries
Data manipulation, visualization, statistical analysis, and machine learning libraries.

In [ ]:
import numpy as np
import pandas as pd
import scipy
from scipy import stats
from collections import Counter
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import norm, t
from scipy.stats import expon
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot,show,title ,xlabel,ylabel
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson
from statsmodels.stats.rates import test_poisson_2indep
from scipy.stats import chi2
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import LeavePOut
from sklearn.model_selection import ShuffleSplit
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LassoCV
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import ElasticNetCV
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn import tree
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import BaggingRegressor
from xgboost import XGBClassifier
from statsmodels.tsa.seasonal import seasonal_decompose
from sklearn.metrics import mean_squared_error
from math import sqrt

# Load Dataset
Read the loan risk dataset into a pandas DataFrame.

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/industry_loan_risk_dataset_100k.csv')

# Initial Data Exploration
Inspect records, data types, duplicates, and missing values.

In [ ]:
df.head()

,Customer_ID,Age,Gender,Marital_Status,Education,Employment_Type,Experience_Years,Annual_Income,City_Tier,Savings_Balance,Credit_Card_Debt,Existing_EMI,Credit_Score,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Past_Loans,Past_Defaults,Monthly_Expense,Loan_Default
0,1000001,23,Female,Divorced,Bachelor,Salaried,0,88377.0,2,55259.0,19806.0,2609.0,NaN,473522.0,48,13.89,0,1,4506.0,1
1,1000002,49,Female,Married,Bachelor,Self-Employed,27,134077.0,2,92131.0,14155.0,2162.0,555.0,730836.0,72,14.34,1,1,6013.0,1
2,1000003,55,Male,Married,Master,Self-Employed,31,153492.0,1,285731.0,40987.0,2366.0,NaN,478732.0,12,16.88,0,0,14026.0,1
3,1000004,59,Male,Divorced,High School,Salaried,38,142566.0,2,387367.0,143125.0,1470.0,507.0,588353.0,12,16.42,1,0,4000.0,1
4,1000005,38,Female,Married,PhD,Salaried,15,166374.0,1,592917.0,229999.0,5609.0,490.0,809548.0,24,14.44,1,0,17308.0,1

# Data Cleaning
Remove duplicates and analyze missing data.

In [ ]:
df.nunique()

Customer_ID           100000
Age                       45
Gender                     2
Marital_Status             3
Education                  4
Employment_Type            3
Experience_Years          45
Annual_Income          68782
City_Tier                  3
Savings_Balance        87055
Credit_Card_Debt       77655
Existing_EMI            7324
Credit_Score             388
Loan_Amount            93541
Loan_Tenure_Months         7
Interest_Rate           1131
Past_Loans                12
Past_Defaults              4
Monthly_Expense         9382
Loan_Default               2
dtype: int64

# Convert Categorical Variables
Convert object columns into category datatype.

In [ ]:
df=df.drop_duplicates()

# Missing Value Indicators
Create binary flags for missing values.

In [ ]:
df.nunique()

Customer_ID           100000
Age                       45
Gender                     2
Marital_Status             3
Education                  4
Employment_Type            3
Experience_Years          45
Annual_Income          68782
City_Tier                  3
Savings_Balance        87055
Credit_Card_Debt       77655
Existing_EMI            7324
Credit_Score             388
Loan_Amount            93541
Loan_Tenure_Months         7
Interest_Rate           1131
Past_Loans                12
Past_Defaults              4
Monthly_Expense         9382
Loan_Default               2
dtype: int64

# Annual Income Prediction (OLS)
Build a regression model to analyze Annual Income relationships.

In [ ]:
df.isnull().sum()

Customer_ID              0
Age                      0
Gender                   0
Marital_Status           0
Education                0
Employment_Type          0
Experience_Years         0
Annual_Income         5420
City_Tier                0
Savings_Balance       4121
Credit_Card_Debt         0
Existing_EMI             0
Credit_Score          3409
Loan_Amount              0
Loan_Tenure_Months       0
Interest_Rate            0
Past_Loans               0
Past_Defaults            0
Monthly_Expense       4548
Loan_Default             0
dtype: int64

# Annual Income Imputation
Fill missing Annual Income values using grouped medians.

In [ ]:
null_value_cols=["Annual_Income","Savings_Balance","Credit_Score","Monthly_Expense"]

# Savings Balance Prediction (OLS)
Analyze factors affecting Savings Balance.

In [ ]:
df[null_value_cols].isnull().sum()

Annual_Income      5420
Savings_Balance    4121
Credit_Score       3409
Monthly_Expense    4548
dtype: int64

# Savings Balance Imputation
Impute missing Savings Balance values.

In [ ]:
(df[null_value_cols].isnull().sum()/len(df))*100

Annual_Income      5.420
Savings_Balance    4.121
Credit_Score       3.409
Monthly_Expense    4.548
dtype: float64

# Credit Score Prediction (OLS)
Analyze drivers of customer credit scores.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Customer_ID         100000 non-null  int64
 1   Age                 100000 non-null  int64
 2   Gender              100000 non-null  object
 3   Marital_Status      100000 non-null  object
 4   Education           100000 non-null  object
 5   Employment_Type     100000 non-null  object
 6   Experience_Years    100000 non-null  int64
 7   Annual_Income       94580 non-null   float64
 8   City_Tier           100000 non-null  int64
 9   Savings_Balance     95879 non-null   float64
 10  Credit_Card_Debt    100000 non-null  float64
 11  Existing_EMI        100000 non-null  float64
 12  Credit_Score        96591 non-null   float64
 13  Loan_Amount         100000 non-null  float64
 14  Loan_Tenure_Months  100000 non-null  int64
 15  Interest_Rate       100000 non-null  float64
 16  Past_Loans          100000 non-null  int64
 17  Past_Defaults       100000 non-null  int64
 18  Monthly_Expense     95452 non-null   float64
 19  Loan_Default        100000 non-null  int64
dtypes: float64(8), int64(8), object(4)
memory usage: 15.3+ MB

#Converting DataTypes

# Credit Score Imputation
Fill missing Credit Score values.

In [ ]:
cat=["Gender","Marital_Status","Education","Employment_Type"]

# Monthly Expense Prediction (OLS)
Analyze spending patterns.

In [ ]:
for i in cat:
  df[i]=df[i].astype("category")

# Monthly Expense Imputation
Fill missing Monthly Expense values.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Customer_ID              100000 non-null  int64
 1   Age                      100000 non-null  int64
 2   Gender                   100000 non-null  category
 3   Marital_Status           100000 non-null  category
 4   Education                100000 non-null  category
 5   Employment_Type          100000 non-null  category
 6   Experience_Years         100000 non-null  int64
 7   Annual_Income            94580 non-null   float64
 8   City_Tier                100000 non-null  int64
 9   Savings_Balance          95879 non-null   float64
 10  Credit_Card_Debt         100000 non-null  float64
 11  Existing_EMI             100000 non-null  float64
 12  Credit_Score             96591 non-null   float64
 13  Loan_Amount              100000 non-null  float64
 14  Loan_Tenure_Months       100000 non-null  int64
 15  Interest_Rate            100000 non-null  float64
 16  Past_Loans               100000 non-null  int64
 17  Past_Defaults            100000 non-null  int64
 18  Monthly_Expense          95452 non-null   float64
 19  Loan_Default             100000 non-null  int64
 20  Annual_Income_Missing    100000 non-null  int64
 21  Savings_Balance_Missing  100000 non-null  int64
 22  Credit_Score_Missing     100000 non-null  int64
 23  Monthly_Expense_Missing  100000 non-null  int64
dtypes: category(4), float64(8), int64(12)
memory usage: 15.6 MB

# Logistic Regression Model
Train a baseline classifier for loan default prediction.

In [ ]:
for i in null_value_cols:
  df[i+"_Missing"]=df[i].isnull().astype(int)

# XGBoost Model
Train an advanced boosting model and compare performance.

In [ ]:
df.describe()

,Customer_ID,Age,Experience_Years,Annual_Income,City_Tier,Savings_Balance,Credit_Card_Debt,Existing_EMI,Credit_Score,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Past_Loans,Past_Defaults,Monthly_Expense,Loan_Default,Annual_Income_Missing,Savings_Balance_Missing,Credit_Score_Missing,Monthly_Expense_Missing
count,1.000000e+05,100000.00000,100000.000000,94580.000000,100000.000000,95879.000000,100000.000000,100000.000000,96591.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,95452.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,1.050000e+06,43.04838,17.913920,112047.787904,2.100100,234486.919503,86716.968780,2433.339350,549.621062,3.757159e+05,48.055800,15.501416,1.992130,0.242440,6081.072089,0.685280,0.054200,0.041210,0.034090,0.045480
std,2.886766e+04,12.96091,12.706565,37788.119578,0.699646,151868.628286,57444.806064,1597.452777,61.593743,3.088972e+05,24.038694,1.620661,1.412433,0.472594,2371.560578,0.464407,0.226413,0.198777,0.181461,0.208355
min,1.000001e+06,21.00000,0.000000,15000.000000,1.000000,4127.000000,940.000000,32.000000,330.000000,7.787000e+03,12.000000,8.360000,0.000000,0.000000,4000.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.025001e+06,32.00000,6.000000,84135.500000,2.000000,111738.000000,40127.500000,1142.000000,504.000000,1.827048e+05,24.000000,14.410000,1.000000,0.000000,4000.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.050000e+06,43.00000,18.000000,111068.000000,2.000000,208760.000000,77228.000000,2171.000000,549.000000,3.271990e+05,48.000000,15.500000,2.000000,0.000000,5317.500000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1.075000e+06,54.00000,29.000000,138344.000000,3.000000,331033.500000,123858.250000,3455.000000,595.000000,5.099288e+05,72.000000,16.600000,3.000000,0.000000,7503.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,1.100000e+06,65.00000,44.000000,254844.000000,3.000000,923853.000000,355673.000000,10057.000000,757.000000,9.990880e+06,84.000000,23.090000,11.000000,3.000000,21421.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df.head()

,Customer_ID,Age,Gender,Marital_Status,Education,Employment_Type,Experience_Years,Annual_Income,City_Tier,Savings_Balance,Credit_Card_Debt,Existing_EMI,Credit_Score,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Past_Loans,Past_Defaults,Monthly_Expense,Loan_Default,Annual_Income_Missing,Savings_Balance_Missing,Credit_Score_Missing,Monthly_Expense_Missing
0,1000001,23,Female,Divorced,Bachelor,Salaried,0,88377.0,2,55259.0,19806.0,2609.0,NaN,473522.0,48,13.89,0,1,4506.0,1,0,0,1,0
1,1000002,49,Female,Married,Bachelor,Self-Employed,27,134077.0,2,92131.0,14155.0,2162.0,555.0,730836.0,72,14.34,1,1,6013.0,1,0,0,0,0
2,1000003,55,Male,Married,Master,Self-Employed,31,153492.0,1,285731.0,40987.0,2366.0,NaN,478732.0,12,16.88,0,0,14026.0,1,0,0,1,0
3,1000004,59,Male,Divorced,High School,Salaried,38,142566.0,2,387367.0,143125.0,1470.0,507.0,588353.0,12,16.42,1,0,4000.0,1,0,0,0,0
4,1000005,38,Female,Married,PhD,Salaried,15,166374.0,1,592917.0,229999.0,5609.0,490.0,809548.0,24,14.44,1,0,17308.0,1,0,0,0,0

In [ ]:
df_income=df[df["Annual_Income"].notnull()].copy()

In [ ]:
df_income

,Customer_ID,Age,Gender,Marital_Status,Education,Employment_Type,Experience_Years,Annual_Income,City_Tier,Savings_Balance,Credit_Card_Debt,Existing_EMI,Credit_Score,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Past_Loans,Past_Defaults,Monthly_Expense,Loan_Default,Annual_Income_Missing,Savings_Balance_Missing,Credit_Score_Missing,Monthly_Expense_Missing
0,1000001,23,Female,Divorced,Bachelor,Salaried,0,88377.0,2,55259.0,19806.0,2609.0,NaN,473522.0,48,13.89,0,1,4506.0,1,0,0,1,0
1,1000002,49,Female,Married,Bachelor,Self-Employed,27,134077.0,2,92131.0,14155.0,2162.0,555.0,730836.0,72,14.34,1,1,6013.0,1,0,0,0,0
2,1000003,55,Male,Married,Master,Self-Employed,31,153492.0,1,285731.0,40987.0,2366.0,NaN,478732.0,12,16.88,0,0,14026.0,1,0,0,1,0
3,1000004,59,Male,Divorced,High School,Salaried,38,142566.0,2,387367.0,143125.0,1470.0,507.0,588353.0,12,16.42,1,0,4000.0,1,0,0,0,0
4,1000005,38,Female,Married,PhD,Salaried,15,166374.0,1,592917.0,229999.0,5609.0,490.0,809548.0,24,14.44,1,0,17308.0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1099996,29,Female,Married,Bachelor,Salaried,3,90591.0,3,325437.0,33520.0,2304.0,643.0,89629.0,84,15.89,2,0,4104.0,0,0,0,0,0
99996,1099997,26,Male,Married,Bachelor,Salaried,2,88112.0,2,105200.0,43856.0,2553.0,648.0,347296.0,36,13.87,2,0,4000.0,1,0,0,0,0
99997,1099998,21,Female,Married,Bachelor,Salaried,0,42319.0,2,47991.0,59897.0,316.0,460.0,169243.0,24,16.70,2,0,4000.0,1,0,0,0,0
99998,1099999,38,Female,Single,Bachelor,Salaried,11,55264.0,2,93814.0,24889.0,2250.0,589.0,166910.0,60,16.02,2,0,6256.0,1,0,0,0,0
99999,1100000,50,Male,Married,Master,Salaried,20,155774.0,2,432661.0,207455.0,1595.0,540.0,915424.0,72,15.22,3,0,8731.0,1,0,0,0,0

In [ ]:
continuous_cols=["Age","Experience_Years","City_Tier","Past_Loans","Past_Defaults"]
categorical_cols=["Gender","Education","Employment_Type","Marital_Status"]

#OneHotEncoding

In [ ]:
df_encoding=pd.get_dummies(df_income,columns=categorical_cols,drop_first=True)

In [ ]:
df_encoding.head()

,Customer_ID,Age,Experience_Years,Annual_Income,City_Tier,Savings_Balance,Credit_Card_Debt,Existing_EMI,Credit_Score,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Past_Loans,Past_Defaults,Monthly_Expense,Loan_Default,Annual_Income_Missing,Savings_Balance_Missing,Credit_Score_Missing,Monthly_Expense_Missing,Gender_Male,Education_High School,Education_Master,Education_PhD,Employment_Type_Salaried,Employment_Type_Self-Employed,Marital_Status_Married,Marital_Status_Single
0,1000001,23,0,88377.0,2,55259.0,19806.0,2609.0,NaN,473522.0,48,13.89,0,1,4506.0,1,0,0,1,0,False,False,False,False,True,False,False,False
1,1000002,49,27,134077.0,2,92131.0,14155.0,2162.0,555.0,730836.0,72,14.34,1,1,6013.0,1,0,0,0,0,False,False,False,False,False,True,True,False
2,1000003,55,31,153492.0,1,285731.0,40987.0,2366.0,NaN,478732.0,12,16.88,0,0,14026.0,1,0,0,1,0,True,False,True,False,False,True,True,False
3,1000004,59,38,142566.0,2,387367.0,143125.0,1470.0,507.0,588353.0,12,16.42,1,0,4000.0,1,0,0,0,0,True,True,False,False,True,False,False,False
4,1000005,38,15,166374.0,1,592917.0,229999.0,5609.0,490.0,809548.0,24,14.44,1,0,17308.0,1,0,0,0,0,False,False,False,True,True,False,True,False

In [ ]:
x = df_encoding[
[
"Age",
"Experience_Years",
"City_Tier",
"Past_Loans",
"Past_Defaults",
"Gender_Male",
"Education_High School",
"Education_Master",
"Education_PhD",
"Employment_Type_Salaried",
"Employment_Type_Self-Employed",
"Marital_Status_Married",
"Marital_Status_Single"
]
]

In [ ]:
y = df_encoding["Annual_Income"]

In [ ]:
temp = pd.concat([x,y],axis=1).dropna()

In [ ]:
x = temp.drop("Annual_Income", axis=1)
y = temp["Annual_Income"]

In [ ]:
x=sm.add_constant(x)

In [ ]:
x = x.astype(float)

In [ ]:
print(x.dtypes.value_counts())

float64    14
Name: count, dtype: int64

In [ ]:
print(x.isnull().sum().sum())

0

In [ ]:
mod=sm.OLS(y,x).fit()

In [ ]:
print(mod.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          Annual_Income   R-squared:                       0.842
Model:                            OLS   Adj. R-squared:                  0.842
Method:                 Least Squares   F-statistic:                 3.865e+04
Date:                Sat, 13 Jun 2026   Prob (F-statistic):               0.00
Time:                        16:10:55   Log-Likelihood:            -1.0439e+06
No. Observations:               94580   AIC:                         2.088e+06
Df Residuals:                   94566   BIC:                         2.088e+06
Df Model:                          13
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const                          4.458e+04    523.038     85.236      0.000    4.36e+04    4.56e+04
Age                             996.7802     17.174     58.039      0.000     963.119    1030.442
Experience_Years               1205.9437     17.520     68.833      0.000    1171.605    1240.283
City_Tier                        72.7027     69.914      1.040      0.298     -64.328     209.733
Past_Loans                       18.1916     34.645      0.525      0.600     -49.712      86.096
Past_Defaults                    42.5033    103.477      0.411      0.681    -160.310     245.317
Gender_Male                     -70.5450     98.311     -0.718      0.473    -263.234     122.144
Education_High School         -2.001e+04    116.963   -171.056      0.000   -2.02e+04   -1.98e+04
Education_Master               2.514e+04    130.559    192.577      0.000    2.49e+04    2.54e+04
Education_PhD                  6.029e+04    230.136    261.958      0.000    5.98e+04    6.07e+04
Employment_Type_Salaried         93.8242    175.348      0.535      0.593    -249.856     437.505
Employment_Type_Self-Employed    24.1062    202.851      0.119      0.905    -373.479     421.692
Marital_Status_Married          283.1771    166.836      1.697      0.090     -43.819     610.173
Marital_Status_Single           220.1963    174.121      1.265      0.206    -121.080     561.472
==============================================================================
Omnibus:                        1.598   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.450   Jarque-Bera (JB):                1.607
Skew:                           0.009   Prob(JB):                        0.448
Kurtosis:                       2.993   Cond. No.                         544.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

influened cols on anual income are:
AGE,Experience_Years,Education

so while filling null values in annual income we will considered these 3 cols

In [ ]:
df["Age_Band"] = pd.cut(
    df["Age"],
    bins=[20,30,40,50,60,70]
)
df["Age_Band"]

0        (20, 30]
1        (40, 50]
2        (50, 60]
3        (50, 60]
4        (30, 40]
           ...
99995    (20, 30]
99996    (20, 30]
99997    (20, 30]
99998    (30, 40]
99999    (40, 50]
Name: Age_Band, Length: 100000, dtype: category
Categories (5, interval[int64, right]): [(20, 30] < (30, 40] < (40, 50] < (50, 60] < (60, 70]]

In [ ]:
df["Exp_Band"] = pd.cut(
    df["Experience_Years"],
    bins=[-1,5,10,20,30,40,60]
)

In [ ]:
df["Annual_Income"] = df["Annual_Income"].fillna(
    df.groupby(
        ["Education","Age_Band","Exp_Band"]
    )["Annual_Income"].transform("median")
)

In [ ]:
df["Annual_Income"].isnull().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Customer_ID                   0
Age                           0
Gender                        0
Marital_Status                0
Education                     0
Employment_Type               0
Experience_Years              0
Annual_Income                 0
City_Tier                     0
Savings_Balance            4121
Credit_Card_Debt              0
Existing_EMI                  0
Credit_Score               3409
Loan_Amount                   0
Loan_Tenure_Months            0
Interest_Rate                 0
Past_Loans                    0
Past_Defaults                 0
Monthly_Expense            4548
Loan_Default                  0
Annual_Income_Missing         0
Savings_Balance_Missing       0
Credit_Score_Missing          0
Monthly_Expense_Missing       0
Age_Band                      0
Exp_Band                      0
dtype: int64

In [ ]:
df["Savings_Balance"].isnull().sum()

np.int64(4121)

In [ ]:
df["Savings_Balance"].isnull().sum()/len(df)*100

np.float64(4.1209999999999996)

In [ ]:
df.head()

,Customer_ID,Age,Gender,Marital_Status,Education,Employment_Type,Experience_Years,Annual_Income,City_Tier,Savings_Balance,Credit_Card_Debt,Existing_EMI,Credit_Score,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Past_Loans,Past_Defaults,Monthly_Expense,Loan_Default,Annual_Income_Missing,Savings_Balance_Missing,Credit_Score_Missing,Monthly_Expense_Missing,Age_Band,Exp_Band
0,1000001,23,Female,Divorced,Bachelor,Salaried,0,88377.0,2,55259.0,19806.0,2609.0,NaN,473522.0,48,13.89,0,1,4506.0,1,0,0,1,0,"(20, 30]","(-1, 5]"
1,1000002,49,Female,Married,Bachelor,Self-Employed,27,134077.0,2,92131.0,14155.0,2162.0,555.0,730836.0,72,14.34,1,1,6013.0,1,0,0,0,0,"(40, 50]","(20, 30]"
2,1000003,55,Male,Married,Master,Self-Employed,31,153492.0,1,285731.0,40987.0,2366.0,NaN,478732.0,12,16.88,0,0,14026.0,1,0,0,1,0,"(50, 60]","(30, 40]"
3,1000004,59,Male,Divorced,High School,Salaried,38,142566.0,2,387367.0,143125.0,1470.0,507.0,588353.0,12,16.42,1,0,4000.0,1,0,0,0,0,"(50, 60]","(30, 40]"
4,1000005,38,Female,Married,PhD,Salaried,15,166374.0,1,592917.0,229999.0,5609.0,490.0,809548.0,24,14.44,1,0,17308.0,1,0,0,0,0,"(30, 40]","(10, 20]"

In [ ]:
num_cols = [
    "Age",
    "Experience_Years",
    "Annual_Income",
    "Credit_Score",
    "Monthly_Expense",
    "Savings_Balance"
]

df[num_cols].corr()["Savings_Balance"].sort_values(ascending=False)

Savings_Balance     1.000000
Annual_Income       0.520283
Experience_Years    0.386681
Age                 0.385969
Monthly_Expense     0.279908
Credit_Score        0.067887
Name: Savings_Balance, dtype: float64

now fii=lling null values in saving_balance

In [ ]:
y = df_encoding["Savings_Balance"]

In [ ]:
x = df_encoding[
[
"Age",
"Experience_Years",
"Annual_Income",
"Credit_Score",
"Monthly_Expense",
"Gender_Male",
"Education_High School",
"Education_Master",
"Education_PhD",
"Employment_Type_Salaried",
"Employment_Type_Self-Employed",
"Marital_Status_Married",
"Marital_Status_Single"
]
]

In [ ]:
temp = pd.concat([x,y],axis=1).dropna()

In [ ]:
x = temp.drop("Savings_Balance",axis=1)
y = temp["Savings_Balance"]

In [ ]:
x = sm.add_constant(x)

In [ ]:
x = x.astype(float)

In [ ]:
mod1 = sm.OLS(y,x).fit()

In [ ]:
print(mod1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Savings_Balance   R-squared:                       0.273
Model:                            OLS   Adj. R-squared:                  0.273
Method:                 Least Squares   F-statistic:                     2412.
Date:                Sat, 13 Jun 2026   Prob (F-statistic):               0.00
Time:                        16:36:07   Log-Likelihood:            -1.1029e+06
No. Observations:               83614   AIC:                         2.206e+06
Df Residuals:                   83600   BIC:                         2.206e+06
Df Model:                          13
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const                           972.3470   6145.678      0.158      0.874   -1.11e+04     1.3e+04
Age                            -157.5589    160.133     -0.984      0.325    -471.419     156.301
Experience_Years                178.0779    164.631      1.082      0.279    -144.597     500.752
Annual_Income                     2.0913      0.031     68.069      0.000       2.031       2.152
Credit_Score                      6.8537      7.332      0.935      0.350      -7.517      21.224
Monthly_Expense                   0.0607      0.224      0.271      0.786      -0.378       0.499
Gender_Male                   -1048.5693    900.846     -1.164      0.244   -2814.220     717.081
Education_High School           129.3396   1226.801      0.105      0.916   -2275.180    2533.859
Education_Master                208.4871   1410.928      0.148      0.883   -2556.921    2973.895
Education_PhD                   145.7393   2768.381      0.053      0.958   -5280.266    5571.745
Employment_Type_Salaried        542.3687   1611.142      0.337      0.736   -2615.458    3700.195
Employment_Type_Self-Employed  1536.7489   1862.005      0.825      0.409   -2112.766    5186.264
Marital_Status_Married        -1516.5230   1496.084     -1.014      0.311   -4448.836    1415.790
Marital_Status_Single          -685.0847   1584.350     -0.432      0.665   -3790.398    2420.229
==============================================================================
Omnibus:                     1359.254   Durbin-Watson:                   2.011
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              772.577
Skew:                           0.010   Prob(JB):                    1.73e-168
Kurtosis:                       2.529   Cond. No.                     1.64e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.64e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
df["Income_Band"] = pd.qcut(
    df["Annual_Income"],
    q=5,
    duplicates="drop"
)

In [ ]:
df["Savings_Balance"] = df["Savings_Balance"].fillna(
    df.groupby(
        ["Income_Band"]
    )["Savings_Balance"].transform("median")
)

In [ ]:
df["Savings_Balance"].isnull().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Customer_ID                   0
Age                           0
Gender                        0
Marital_Status                0
Education                     0
Employment_Type               0
Experience_Years              0
Annual_Income                 0
City_Tier                     0
Savings_Balance               0
Credit_Card_Debt              0
Existing_EMI                  0
Credit_Score               3409
Loan_Amount                   0
Loan_Tenure_Months            0
Interest_Rate                 0
Past_Loans                    0
Past_Defaults                 0
Monthly_Expense            4548
Loan_Default                  0
Annual_Income_Missing         0
Savings_Balance_Missing       0
Credit_Score_Missing          0
Monthly_Expense_Missing       0
Age_Band                      0
Exp_Band                      0
Income_Band                   0
dtype: int64

In [ ]:
x = df_encoding[
[
"Annual_Income",
"Savings_Balance",
"Credit_Card_Debt",
"Existing_EMI",
"Loan_Amount",
"Past_Loans",
"Past_Defaults",
"Age",
"Experience_Years"
]
]

In [ ]:
y = df_encoding["Credit_Score"]

In [ ]:
temp = pd.concat([x,y],axis=1).dropna()

In [ ]:
x = temp.drop("Credit_Score",axis=1)
y = temp["Credit_Score"]

In [ ]:
x = sm.add_constant(x)

In [ ]:
mod2 = sm.OLS(y,x).fit()

In [ ]:
print(mod2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           Credit_Score   R-squared:                       0.610
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                 1.520e+04
Date:                Sat, 13 Jun 2026   Prob (F-statistic):               0.00
Time:                        18:00:29   Log-Likelihood:            -4.4397e+05
No. Observations:               87588   AIC:                         8.880e+05
Df Residuals:                   87578   BIC:                         8.881e+05
Df Model:                           9
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const              527.1116      1.216    433.470      0.000     524.728     529.495
Annual_Income        0.0010   6.47e-06    147.046      0.000       0.001       0.001
Savings_Balance  -4.809e-07      1e-06     -0.480      0.631   -2.45e-06    1.48e-06
Credit_Card_Debt    -0.0010   2.63e-06   -365.209      0.000      -0.001      -0.001
Existing_EMI     -3.519e-05    9.5e-05     -0.370      0.711      -0.000       0.000
Loan_Amount      -5.704e-07    4.6e-07     -1.241      0.215   -1.47e-06     3.3e-07
Past_Loans           0.0344      0.094      0.366      0.714      -0.150       0.218
Past_Defaults        0.8055      0.275      2.931      0.003       0.267       1.344
Age                 -0.0058      0.046     -0.126      0.900      -0.096       0.084
Experience_Years    -0.0174      0.047     -0.370      0.711      -0.109       0.075
==============================================================================
Omnibus:                        5.319   Durbin-Watson:                   2.009
Prob(Omnibus):                  0.070   Jarque-Bera (JB):                5.406
Skew:                          -0.009   Prob(JB):                       0.0670
Kurtosis:                       3.034   Cond. No.                     5.14e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.14e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
df["Income_Band"] = pd.qcut(
    df["Annual_Income"],
    q=5,
    duplicates="drop"
)

df["Debt_Band"] = pd.qcut(
    df["Credit_Card_Debt"],
    q=5,
    duplicates="drop"
)

In [ ]:
df["Credit_Score"] = df["Credit_Score"].fillna(
    df.groupby(
        ["Income_Band", "Debt_Band", "Past_Defaults"]
    )["Credit_Score"].transform("median")
)

In [ ]:
df["Credit_Score"].isnull().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Customer_ID                   0
Age                           0
Gender                        0
Marital_Status                0
Education                     0
Employment_Type               0
Experience_Years              0
Annual_Income                 0
City_Tier                     0
Savings_Balance               0
Credit_Card_Debt              0
Existing_EMI                  0
Credit_Score                  0
Loan_Amount                   0
Loan_Tenure_Months            0
Interest_Rate                 0
Past_Loans                    0
Past_Defaults                 0
Monthly_Expense            4548
Loan_Default                  0
Annual_Income_Missing         0
Savings_Balance_Missing       0
Credit_Score_Missing          0
Monthly_Expense_Missing       0
Age_Band                      0
Exp_Band                      0
Income_Band                   0
Debt_Band                     0
dtype: int64

In [ ]:
x = df_encoding[
[
"Annual_Income",
"Savings_Balance",
"Credit_Card_Debt",
"Existing_EMI",
"Age",
"Experience_Years",
"Employment_Type_Salaried",
"Employment_Type_Self-Employed"
]
]

In [ ]:
y= df_encoding["Monthly_Expense"]

In [ ]:
temp = pd.concat([x,y],axis=1).dropna()

In [ ]:
x = temp.drop("Monthly_Expense",axis=1)
y = temp["Monthly_Expense"]

In [ ]:
x = sm.add_constant(x)

In [ ]:
x = x.astype(float)

In [ ]:
mod3 = sm.OLS(y,x).fit()

In [ ]:
print(mod3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Monthly_Expense   R-squared:                       0.286
Model:                            OLS   Adj. R-squared:                  0.286
Method:                 Least Squares   F-statistic:                     4340.
Date:                Sat, 13 Jun 2026   Prob (F-statistic):               0.00
Time:                        18:57:48   Log-Likelihood:            -7.8104e+05
No. Observations:               86577   AIC:                         1.562e+06
Df Residuals:                   86568   BIC:                         1.562e+06
Df Model:                           8
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const                          2530.0917     66.539     38.024      0.000    2399.675    2660.508
Annual_Income                     0.0349      0.000    106.309      0.000       0.034       0.036
Savings_Balance                1.075e-05   5.26e-05      0.205      0.838   -9.22e-05       0.000
Credit_Card_Debt                 -0.0001      0.000     -0.991      0.321      -0.000       0.000
Existing_EMI                     -0.0145      0.005     -2.911      0.004      -0.024      -0.005
Age                              -7.7826      2.406     -3.234      0.001     -12.499      -3.066
Experience_Years                  3.9130      2.459      1.592      0.111      -0.906       8.732
Employment_Type_Salaried        -58.5713     24.462     -2.394      0.017    -106.516     -10.627
Employment_Type_Self-Employed   -46.7628     28.288     -1.653      0.098    -102.207       8.682
==============================================================================
Omnibus:                     8196.563   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11060.464
Skew:                           0.789   Prob(JB):                         0.00
Kurtosis:                       3.759   Cond. No.                     3.10e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.1e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
df["Income_Band"] = pd.qcut(
    df["Annual_Income"],
    q=5,
    duplicates="drop"
)

In [ ]:
df["Monthly_Expense"] = df["Monthly_Expense"].fillna(
    df.groupby(
        ["Income_Band"]
    )["Monthly_Expense"].transform("median")
)

In [ ]:
df["Monthly_Expense"].isnull().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Customer_ID                0
Age                        0
Gender                     0
Marital_Status             0
Education                  0
Employment_Type            0
Experience_Years           0
Annual_Income              0
City_Tier                  0
Savings_Balance            0
Credit_Card_Debt           0
Existing_EMI               0
Credit_Score               0
Loan_Amount                0
Loan_Tenure_Months         0
Interest_Rate              0
Past_Loans                 0
Past_Defaults              0
Monthly_Expense            0
Loan_Default               0
Annual_Income_Missing      0
Savings_Balance_Missing    0
Credit_Score_Missing       0
Monthly_Expense_Missing    0
Age_Band                   0
Exp_Band                   0
Income_Band                0
Debt_Band                  0
dtype: int64

#LogisticRegression

In [ ]:
df_model1 = df.copy()

In [ ]:
x = df.drop(["Loan_Default", "Customer_ID"], axis=1)
y = df["Loan_Default"]

In [ ]:
x = pd.get_dummies(x, drop_first=True)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
print(model.score(x_train, y_train))
print(model.score(x_test, y_test))

0.8368125
0.83745

#XGBoost

In [ ]:
X = df.drop(["Loan_Default", "Customer_ID"], axis=1)
y = df["Loan_Default"]

In [ ]:
X = pd.get_dummies(X, drop_first=True)

In [ ]:
X.columns = X.columns.str.replace(r"[\[\]\<\>]", "_", regex=True)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
print(model.score(X_train, y_train))
print(model.score(X_test, y_test))

0.8661375
0.84225